[package]
name = "rust-knowledge-search"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1", features = ["v4"] }
thiserror = "2.0.17"
clap = { version = "4.5.3", features = ["derive"] }
notify = "8.2.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
